In [2]:
import numpy as np 

In [3]:
a = np.array((0,1,2,3),dtype=np.float64)
a

array([0., 1., 2., 3.])

In [4]:
b = np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
a.shape

(4,)

In [6]:
b.shape

(2, 4)

In [7]:
type(b)

numpy.ndarray

In [8]:
a.dtype

dtype('float64')

In [9]:
b.dtype

dtype('int32')

In [10]:
b = np.array([[0,1,2,3],[4,5,6,7]])
a = b.reshape((4,2))

In [11]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [13]:
b[1][2] = 9999

In [14]:
b

array([[   0,    1,    2,    3],
       [   4,    5, 9999,    7]])

In [15]:
a

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [9999,    7]])

In [16]:
c = a.astype(np.complex)
c

array([[0.000e+00+0.j, 1.000e+00+0.j],
       [2.000e+00+0.j, 3.000e+00+0.j],
       [4.000e+00+0.j, 5.000e+00+0.j],
       [9.999e+03+0.j, 7.000e+00+0.j]])

In [20]:
a[3][1] = 8888

In [21]:
c

array([[0.000e+00+0.j, 1.000e+00+0.j],
       [2.000e+00+0.j, 3.000e+00+0.j],
       [4.000e+00+0.j, 5.000e+00+0.j],
       [9.999e+03+0.j, 7.000e+00+0.j]])

In [22]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [23]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.logspace(0,2,5,endpoint=True)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [26]:
np.zeros((2,3), np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.empty(4,np.float)

array([0., 0., 0., 0.])

In [28]:
np.ones((4,3),np.uint64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint64)

In [29]:
np.full((3,2),np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [31]:
def weekday(i):
    print("call ", i)
    return (i+6) % 7

np.fromfunction(weekday,(31,)).astype(np.int)

call  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


array([6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
       0, 1, 2, 3, 4, 5, 6, 0, 1])

In [ ]:
def multi(i,j):
    return (i+1)*(j+1)

np.fromfunction(multi,(9,9)).astype(int)